test: tweak gen-images() to be smarter about the UUID hacks
osbuild/otk pull request #212
Opened 2024-09-23 11:23 UTC by mvo5

This commit tweaks the gen-images-ref to be slightly smarter about how to handle UUIDs. Instead of the extremly naive table of uuids generated by "images" and "gen-partition-table" it now tries to figure out the UUID from images via the "fstab" stage of the manifest. This is also a bit (f)ugly but avoids some busywork (and will of course break once we have images that do not use a fstab stage).

Hopefully we find a better way but this should give us some time.

2024-09-23 14:29 UTC, mvo5 commented
We will also need to revert https://github.com/osbuild/otk/pull/209/commits/48c9889a32852459c7e7738fd562d13ae3a6a22e here if/after https://github.com/osbuild/otk/pull/209 gets merged (see https://github.com/osbuild/otk/pull/209#pullrequestreview-2321862931)

2024-09-23 15:03 UTC, achilleas-k approved these changes

2024-09-23 15:04 UTC, achilleas-k requested changes
#209 merged.  Let's revert here.

2024-09-26 10:43 UTC, supakeen submitted a review, later dismissed

2024-09-26 10:46 UTC, mvo5 commented
> #209 merged. Let's revert here.

The revert from #209 is part of this PR now

2024-09-26 10:46 UTC, achilleas-k approved these changes

2024-09-26 10:47 UTC, achilleas-k commented
Test manifests need updating

2024-09-26 10:52 UTC, supakeen approved these changes

2024-09-26 10:55 UTC, merged